Now handles library name Returns a status   0 if exactly one result   1 if no results   2 if two or more results   3 if utterly confused

diff --git a/mttroot/mtt/bin/mtt_find b/mttroot/mtt/bin/mtt_find
--- a/mttroot/mtt/bin/mtt_find
+++ b/mttroot/mtt/bin/mtt_find
@@ -14,6 +14,9 @@
 ###############################################################
 ## $Id$
 ## $Log$
+## Revision 1.4  1998/07/16 20:40:24  peterg
+## Cleaned up algorithms
+##
 ## Revision 1.3  1998/07/16 09:15:34  peterg
 ## Now prints:
 ## 	dir
@@ -28,21 +31,29 @@
 ##
 ###############################################################
 
+# Set up dummy file
+rm -f mtt_junk
+touch mtt_junk
+
+# Interpret the arguments
 path="$1"
 
-
 if [ -n "$2" ]; then
-    name="-name $2"
+    name=`basename $2`
+    longname=$2
+    Name="-name $name"
 fi
-q=\
 
 
+# Find all dirs in path with same name as component
+# AND the path contains the full (name+library) name
 paths=`echo $path | tr ":" " "`
 foundpath=`\
 for thepath in $paths; do
-    find $thepath -type d  $name -print 
-done | \
-sort -u`
+    find $thepath -type d  $Name -print 
+done |\
+sort -u |\
+grep "$longname"`
 
 # If non-null result, check that the name_lbl.txt file exists in dir name
 # and print dirname and file name and last access time
@@ -52,9 +63,23 @@ if [ -n "$foundpath" ]; then
   dirname=`echo $thepath | awk -F/ '{print $NF}'`
   fullname="$dirname"_lbl.txt
   find $thepath -maxdepth 1 -name $fullname  -printf '%h\t%f\t%Ac\n';
- done
+ done |\
+ tee mtt_junk
 fi
 
+# Check exit status and return 
+hits=`wc mtt_junk | awk '{print $1}'`
+rm -f mtt_junk
+
+if [ $hits = "1" ]; then
+    exit 0
+elif [ $hits = "0" ]; then
+    exit 1
+elif [ $hits > "1" ]; then
+    exit 2
+else
+    exit 3
+fi
 
 
 
