Simple filter for Reduce reserved words in sympar.

diff --git a/mttroot/mtt/bin/trans/mtt_make_sympar b/mttroot/mtt/bin/trans/mtt_make_sympar
--- a/mttroot/mtt/bin/trans/mtt_make_sympar
+++ b/mttroot/mtt/bin/trans/mtt_make_sympar
@@ -13,6 +13,9 @@
 ###############################################################
 ## $Id$
 ## $Log$
+## Revision 1.8  2001/07/04 06:00:12  gawthrop
+## Fixed a funny with tr - changed SEPS and REPS - something to do with ^
+##
 ## Revision 1.7  2001/04/13 07:14:12  geraint
 ## Implemented lower level lbl.txt recognition of #NOT[V|P]AR
 ##
@@ -94,3 +97,25 @@ END{
         printf("\n")
 
 }' < mtt_sympar.txt >$filename
+
+reserved_words=`\
+    cat ${MTT_LIB}/reduce/reserved_words.txt	|\
+    awk '{printf "%s ", $0}'			|\
+    tr [a-z] [A-Z]`
+sympar_words=`\
+    cat ${filename}				|\
+    cut -f1					|\
+    awk '{printf "%s ", $0}'			|\
+    tr [a-z] [A-Z]`
+flag=0
+for reserved_word in ${reserved_words}; do
+    for sympar_word in ${sympar_words}; do
+	if [ ${sympar_word} = ${reserved_word} ]; then
+	    echo "*** MTT Error: ${sympar_word} is reserved (Reduce)"
+	    flag=1
+	fi
+    done
+done
+if [ ${flag} -eq 1 ]; then
+    exit 1;
+fi
